platform:
  - x64

environment:
  matrix:
  - nodejs_version: "20"

install:
  - cmd: git submodule update --init
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install -g node-gyp

build_script:
  - npm install --ignore-scripts
  - npm run rebuild

test_script:
  - npm test

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") {./node_modules/.bin/prebuild -t 14.0.0 -t 16.0.0 -t 18.0.0 --strip -u $env:GITHUB_TOKEN --include-regex "\.(node|dll)$"}
